### PR TITLE
Added PnP.js and userId token as example

### PR DESCRIPTION
**Pull request by RodCoder**
Hi Elio,

Thought it would be a good idea to add PnP.js so we could have more tokens, also added the userId token as example and "getuserbyid('{userId}')" to the known apis. Hope you find it useful.

Another thing is that, selecting suggestions was a bit inconsistent for me, think href and onClick were conflicting. I've moved the onClick event to the li element and works every time... have a look.

Thanks,

Rod

### CODE REVIEW

**Comment by RodCoder** [comment]
Second commit was to make the render function asynchronous. This way we can use async await with the pnp methods :)

**Comment by estruyf** [comment]
@RodCoder thanks for the PR. Appreciate that you want to contribute!

The purpose of this web part is to keep it closely aligned to what SPFx by default gives you. This makes it easier for the developer using it, and for the code snippet creation. Like for example in the case of the user ID property, the developer wouldn't know where it is coming from. So I think it is best, for now, to not mix both things and not merge this PR (or not completely). Although PnP JS Core is a great library which I also like to use, and maybe in the future we could show how you can do certain API calls in a PnP JS way.

Besides that, there is another reason why I'm not going to merge it. The reason is that the `pageContext.legacyPageContext` object can also provide the `userId`, and this would also allow it to get it included in the code snippets.

**Comment by estruyf** [comment]
About the change, you did for the suggestion selection. I could reproduce it on my side but also had it with changing the `onClick` event to the list item. Apparently, it has to do with `onBlur` which hides the suggestions. I changed the timeout to 0,5 second, first tests seem to run a lot better.

**Comment by RodCoder** [comment]
Hi Elio,

Completely understand, as mentioned, this was more of a suggestion in form of a PR. Doesn't make much sense understanding what you envisioned for this webpart.
There's always new things to learn, so thanks for the pageContext.legacyPageContext tip :)
Also glad that you were able to understand what was going on with the suggestions. 

Please, so let me know if there's something I can help with.

Thanks,

Rod

**Pull request closed without merging**
